/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AccommodationService } from "../accommodation.service";
import { AccommodationCreateInput } from "./AccommodationCreateInput";
import { Accommodation } from "./Accommodation";
import { AccommodationFindManyArgs } from "./AccommodationFindManyArgs";
import { AccommodationWhereUniqueInput } from "./AccommodationWhereUniqueInput";
import { AccommodationUpdateInput } from "./AccommodationUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";

export class AccommodationControllerBase {
  constructor(protected readonly service: AccommodationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Accommodation })
  async createAccommodation(
    @common.Body() data: AccommodationCreateInput
  ): Promise<Accommodation> {
    return await this.service.createAccommodation({
      data: {
        ...data,

        explorer: data.explorer
          ? {
              connect: data.explorer,
            }
          : undefined,

        host: data.host
          ? {
              connect: data.host,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        location: true,
        amenities: true,

        explorer: {
          select: {
            id: true,
          },
        },

        host: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Accommodation] })
  @ApiNestedQuery(AccommodationFindManyArgs)
  async accommodations(
    @common.Req() request: Request
  ): Promise<Accommodation[]> {
    const args = plainToClass(AccommodationFindManyArgs, request.query);
    return this.service.accommodations({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        location: true,
        amenities: true,

        explorer: {
          select: {
            id: true,
          },
        },

        host: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Accommodation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async accommodation(
    @common.Param() params: AccommodationWhereUniqueInput
  ): Promise<Accommodation | null> {
    const result = await this.service.accommodation({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        location: true,
        amenities: true,

        explorer: {
          select: {
            id: true,
          },
        },

        host: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Accommodation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAccommodation(
    @common.Param() params: AccommodationWhereUniqueInput,
    @common.Body() data: AccommodationUpdateInput
  ): Promise<Accommodation | null> {
    try {
      return await this.service.updateAccommodation({
        where: params,
        data: {
          ...data,

          explorer: data.explorer
            ? {
                connect: data.explorer,
              }
            : undefined,

          host: data.host
            ? {
                connect: data.host,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          location: true,
          amenities: true,

          explorer: {
            select: {
              id: true,
            },
          },

          host: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Accommodation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAccommodation(
    @common.Param() params: AccommodationWhereUniqueInput
  ): Promise<Accommodation | null> {
    try {
      return await this.service.deleteAccommodation({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          location: true,
          amenities: true,

          explorer: {
            select: {
              id: true,
            },
          },

          host: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: AccommodationWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,

        traveler: {
          select: {
            id: true,
          },
        },

        accommodation: {
          select: {
            id: true,
          },
        },

        activity: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  async connectBookings(
    @common.Param() params: AccommodationWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateAccommodation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  async updateBookings(
    @common.Param() params: AccommodationWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateAccommodation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  async disconnectBookings(
    @common.Param() params: AccommodationWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateAccommodation({
      where: params,
      data,
      select: { id: true },
    });
  }
}
