/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TravelerService } from "../traveler.service";
import { TravelerCreateInput } from "./TravelerCreateInput";
import { Traveler } from "./Traveler";
import { TravelerFindManyArgs } from "./TravelerFindManyArgs";
import { TravelerWhereUniqueInput } from "./TravelerWhereUniqueInput";
import { TravelerUpdateInput } from "./TravelerUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";

export class TravelerControllerBase {
  constructor(protected readonly service: TravelerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Traveler })
  async createTraveler(
    @common.Body() data: TravelerCreateInput
  ): Promise<Traveler> {
    return await this.service.createTraveler({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        password: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Traveler] })
  @ApiNestedQuery(TravelerFindManyArgs)
  async travelers(@common.Req() request: Request): Promise<Traveler[]> {
    const args = plainToClass(TravelerFindManyArgs, request.query);
    return this.service.travelers({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        password: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Traveler })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async traveler(
    @common.Param() params: TravelerWhereUniqueInput
  ): Promise<Traveler | null> {
    const result = await this.service.traveler({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Traveler })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTraveler(
    @common.Param() params: TravelerWhereUniqueInput,
    @common.Body() data: TravelerUpdateInput
  ): Promise<Traveler | null> {
    try {
      return await this.service.updateTraveler({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          email: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Traveler })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTraveler(
    @common.Param() params: TravelerWhereUniqueInput
  ): Promise<Traveler | null> {
    try {
      return await this.service.deleteTraveler({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          email: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: TravelerWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,

        traveler: {
          select: {
            id: true,
          },
        },

        accommodation: {
          select: {
            id: true,
          },
        },

        activity: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  async connectBookings(
    @common.Param() params: TravelerWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateTraveler({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  async updateBookings(
    @common.Param() params: TravelerWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateTraveler({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  async disconnectBookings(
    @common.Param() params: TravelerWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateTraveler({
      where: params,
      data,
      select: { id: true },
    });
  }
}
