/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Activity } from "./Activity";
import { ActivityCountArgs } from "./ActivityCountArgs";
import { ActivityFindManyArgs } from "./ActivityFindManyArgs";
import { ActivityFindUniqueArgs } from "./ActivityFindUniqueArgs";
import { CreateActivityArgs } from "./CreateActivityArgs";
import { UpdateActivityArgs } from "./UpdateActivityArgs";
import { DeleteActivityArgs } from "./DeleteActivityArgs";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { Explorer } from "../../explorer/base/Explorer";
import { Host } from "../../host/base/Host";
import { ActivityService } from "../activity.service";
@graphql.Resolver(() => Activity)
export class ActivityResolverBase {
  constructor(protected readonly service: ActivityService) {}

  async _activitiesMeta(
    @graphql.Args() args: ActivityCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Activity])
  async activities(
    @graphql.Args() args: ActivityFindManyArgs
  ): Promise<Activity[]> {
    return this.service.activities(args);
  }

  @graphql.Query(() => Activity, { nullable: true })
  async activity(
    @graphql.Args() args: ActivityFindUniqueArgs
  ): Promise<Activity | null> {
    const result = await this.service.activity(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Activity)
  async createActivity(
    @graphql.Args() args: CreateActivityArgs
  ): Promise<Activity> {
    return await this.service.createActivity({
      ...args,
      data: {
        ...args.data,

        explorer: args.data.explorer
          ? {
              connect: args.data.explorer,
            }
          : undefined,

        host: args.data.host
          ? {
              connect: args.data.host,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Activity)
  async updateActivity(
    @graphql.Args() args: UpdateActivityArgs
  ): Promise<Activity | null> {
    try {
      return await this.service.updateActivity({
        ...args,
        data: {
          ...args.data,

          explorer: args.data.explorer
            ? {
                connect: args.data.explorer,
              }
            : undefined,

          host: args.data.host
            ? {
                connect: args.data.host,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Activity)
  async deleteActivity(
    @graphql.Args() args: DeleteActivityArgs
  ): Promise<Activity | null> {
    try {
      return await this.service.deleteActivity(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Booking], { name: "bookings" })
  async findBookings(
    @graphql.Parent() parent: Activity,
    @graphql.Args() args: BookingFindManyArgs
  ): Promise<Booking[]> {
    const results = await this.service.findBookings(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Explorer, {
    nullable: true,
    name: "explorer",
  })
  async getExplorer(
    @graphql.Parent() parent: Activity
  ): Promise<Explorer | null> {
    const result = await this.service.getExplorer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Host, {
    nullable: true,
    name: "host",
  })
  async getHost(@graphql.Parent() parent: Activity): Promise<Host | null> {
    const result = await this.service.getHost(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
