/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { HostService } from "../host.service";
import { HostCreateInput } from "./HostCreateInput";
import { Host } from "./Host";
import { HostFindManyArgs } from "./HostFindManyArgs";
import { HostWhereUniqueInput } from "./HostWhereUniqueInput";
import { HostUpdateInput } from "./HostUpdateInput";
import { AccommodationFindManyArgs } from "../../accommodation/base/AccommodationFindManyArgs";
import { Accommodation } from "../../accommodation/base/Accommodation";
import { AccommodationWhereUniqueInput } from "../../accommodation/base/AccommodationWhereUniqueInput";
import { ActivityFindManyArgs } from "../../activity/base/ActivityFindManyArgs";
import { Activity } from "../../activity/base/Activity";
import { ActivityWhereUniqueInput } from "../../activity/base/ActivityWhereUniqueInput";

export class HostControllerBase {
  constructor(protected readonly service: HostService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Host })
  async createHost(@common.Body() data: HostCreateInput): Promise<Host> {
    return await this.service.createHost({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        password: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Host] })
  @ApiNestedQuery(HostFindManyArgs)
  async hosts(@common.Req() request: Request): Promise<Host[]> {
    const args = plainToClass(HostFindManyArgs, request.query);
    return this.service.hosts({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        password: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Host })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async host(
    @common.Param() params: HostWhereUniqueInput
  ): Promise<Host | null> {
    const result = await this.service.host({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        password: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Host })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateHost(
    @common.Param() params: HostWhereUniqueInput,
    @common.Body() data: HostUpdateInput
  ): Promise<Host | null> {
    try {
      return await this.service.updateHost({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          email: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Host })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteHost(
    @common.Param() params: HostWhereUniqueInput
  ): Promise<Host | null> {
    try {
      return await this.service.deleteHost({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          email: true,
          password: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/accommodations")
  @ApiNestedQuery(AccommodationFindManyArgs)
  async findAccommodations(
    @common.Req() request: Request,
    @common.Param() params: HostWhereUniqueInput
  ): Promise<Accommodation[]> {
    const query = plainToClass(AccommodationFindManyArgs, request.query);
    const results = await this.service.findAccommodations(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        location: true,
        amenities: true,

        explorer: {
          select: {
            id: true,
          },
        },

        host: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/accommodations")
  async connectAccommodations(
    @common.Param() params: HostWhereUniqueInput,
    @common.Body() body: AccommodationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accommodations: {
        connect: body,
      },
    };
    await this.service.updateHost({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/accommodations")
  async updateAccommodations(
    @common.Param() params: HostWhereUniqueInput,
    @common.Body() body: AccommodationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accommodations: {
        set: body,
      },
    };
    await this.service.updateHost({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/accommodations")
  async disconnectAccommodations(
    @common.Param() params: HostWhereUniqueInput,
    @common.Body() body: AccommodationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accommodations: {
        disconnect: body,
      },
    };
    await this.service.updateHost({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/activities")
  @ApiNestedQuery(ActivityFindManyArgs)
  async findActivities(
    @common.Req() request: Request,
    @common.Param() params: HostWhereUniqueInput
  ): Promise<Activity[]> {
    const query = plainToClass(ActivityFindManyArgs, request.query);
    const results = await this.service.findActivities(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
        location: true,

        explorer: {
          select: {
            id: true,
          },
        },

        host: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/activities")
  async connectActivities(
    @common.Param() params: HostWhereUniqueInput,
    @common.Body() body: ActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      activities: {
        connect: body,
      },
    };
    await this.service.updateHost({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/activities")
  async updateActivities(
    @common.Param() params: HostWhereUniqueInput,
    @common.Body() body: ActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      activities: {
        set: body,
      },
    };
    await this.service.updateHost({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/activities")
  async disconnectActivities(
    @common.Param() params: HostWhereUniqueInput,
    @common.Body() body: ActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      activities: {
        disconnect: body,
      },
    };
    await this.service.updateHost({
      where: params,
      data,
      select: { id: true },
    });
  }
}
