/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ExplorerService } from "../explorer.service";
import { ExplorerCreateInput } from "./ExplorerCreateInput";
import { Explorer } from "./Explorer";
import { ExplorerFindManyArgs } from "./ExplorerFindManyArgs";
import { ExplorerWhereUniqueInput } from "./ExplorerWhereUniqueInput";
import { ExplorerUpdateInput } from "./ExplorerUpdateInput";
import { AccommodationFindManyArgs } from "../../accommodation/base/AccommodationFindManyArgs";
import { Accommodation } from "../../accommodation/base/Accommodation";
import { AccommodationWhereUniqueInput } from "../../accommodation/base/AccommodationWhereUniqueInput";
import { ActivityFindManyArgs } from "../../activity/base/ActivityFindManyArgs";
import { Activity } from "../../activity/base/Activity";
import { ActivityWhereUniqueInput } from "../../activity/base/ActivityWhereUniqueInput";
import { CommissionFindManyArgs } from "../../commission/base/CommissionFindManyArgs";
import { Commission } from "../../commission/base/Commission";
import { CommissionWhereUniqueInput } from "../../commission/base/CommissionWhereUniqueInput";

export class ExplorerControllerBase {
  constructor(protected readonly service: ExplorerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Explorer })
  async createExplorer(
    @common.Body() data: ExplorerCreateInput
  ): Promise<Explorer> {
    return await this.service.createExplorer({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        email: true,
        password: true,
        name: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Explorer] })
  @ApiNestedQuery(ExplorerFindManyArgs)
  async explorers(@common.Req() request: Request): Promise<Explorer[]> {
    const args = plainToClass(ExplorerFindManyArgs, request.query);
    return this.service.explorers({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        email: true,
        password: true,
        name: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Explorer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async explorer(
    @common.Param() params: ExplorerWhereUniqueInput
  ): Promise<Explorer | null> {
    const result = await this.service.explorer({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        email: true,
        password: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Explorer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateExplorer(
    @common.Param() params: ExplorerWhereUniqueInput,
    @common.Body() data: ExplorerUpdateInput
  ): Promise<Explorer | null> {
    try {
      return await this.service.updateExplorer({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          email: true,
          password: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Explorer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteExplorer(
    @common.Param() params: ExplorerWhereUniqueInput
  ): Promise<Explorer | null> {
    try {
      return await this.service.deleteExplorer({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          email: true,
          password: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/accommodations")
  @ApiNestedQuery(AccommodationFindManyArgs)
  async findAccommodations(
    @common.Req() request: Request,
    @common.Param() params: ExplorerWhereUniqueInput
  ): Promise<Accommodation[]> {
    const query = plainToClass(AccommodationFindManyArgs, request.query);
    const results = await this.service.findAccommodations(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        location: true,
        amenities: true,

        explorer: {
          select: {
            id: true,
          },
        },

        host: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/accommodations")
  async connectAccommodations(
    @common.Param() params: ExplorerWhereUniqueInput,
    @common.Body() body: AccommodationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accommodations: {
        connect: body,
      },
    };
    await this.service.updateExplorer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/accommodations")
  async updateAccommodations(
    @common.Param() params: ExplorerWhereUniqueInput,
    @common.Body() body: AccommodationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accommodations: {
        set: body,
      },
    };
    await this.service.updateExplorer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/accommodations")
  async disconnectAccommodations(
    @common.Param() params: ExplorerWhereUniqueInput,
    @common.Body() body: AccommodationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accommodations: {
        disconnect: body,
      },
    };
    await this.service.updateExplorer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/activities")
  @ApiNestedQuery(ActivityFindManyArgs)
  async findActivities(
    @common.Req() request: Request,
    @common.Param() params: ExplorerWhereUniqueInput
  ): Promise<Activity[]> {
    const query = plainToClass(ActivityFindManyArgs, request.query);
    const results = await this.service.findActivities(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
        location: true,

        explorer: {
          select: {
            id: true,
          },
        },

        host: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/activities")
  async connectActivities(
    @common.Param() params: ExplorerWhereUniqueInput,
    @common.Body() body: ActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      activities: {
        connect: body,
      },
    };
    await this.service.updateExplorer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/activities")
  async updateActivities(
    @common.Param() params: ExplorerWhereUniqueInput,
    @common.Body() body: ActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      activities: {
        set: body,
      },
    };
    await this.service.updateExplorer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/activities")
  async disconnectActivities(
    @common.Param() params: ExplorerWhereUniqueInput,
    @common.Body() body: ActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      activities: {
        disconnect: body,
      },
    };
    await this.service.updateExplorer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/commissions")
  @ApiNestedQuery(CommissionFindManyArgs)
  async findCommissions(
    @common.Req() request: Request,
    @common.Param() params: ExplorerWhereUniqueInput
  ): Promise<Commission[]> {
    const query = plainToClass(CommissionFindManyArgs, request.query);
    const results = await this.service.findCommissions(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        amount: true,

        explorer: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/commissions")
  async connectCommissions(
    @common.Param() params: ExplorerWhereUniqueInput,
    @common.Body() body: CommissionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      commissions: {
        connect: body,
      },
    };
    await this.service.updateExplorer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/commissions")
  async updateCommissions(
    @common.Param() params: ExplorerWhereUniqueInput,
    @common.Body() body: CommissionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      commissions: {
        set: body,
      },
    };
    await this.service.updateExplorer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/commissions")
  async disconnectCommissions(
    @common.Param() params: ExplorerWhereUniqueInput,
    @common.Body() body: CommissionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      commissions: {
        disconnect: body,
      },
    };
    await this.service.updateExplorer({
      where: params,
      data,
      select: { id: true },
    });
  }
}
